version: '3.8'

volumes:
  postgres-medical-data:
  dbdata6:

services:
  medical-db:
    container_name: medical-db
    image: postgres
    restart: always
    ports:
      - '5433:5432'
    environment:
      POSTGRES_PASSWORD: pgmedical
      POSTGRES_DB: medical
    volumes:
      - postgres-medical-data:/var/lib/postgresql/data
    networks:
      - medical-net

networks:
  medical-net:
    name: medical-net
